#!/bin/bash

set -e
grench eval "(do (require 'clojure.tools.namespace.repl) (clojure.tools.namespace.repl/refresh))"
grench eval "(do (require 'clojure.test) (clojure.test/run-all-tests #\"shoutout.*\"))"
